MVVM pattern
  https://www.youtube.com/watch?v=W1e7d3cvnRo #Google Flutter - MVVM in Flutter using Providers.
  https://github.com/azamsharp/Movies-App-Flutter-MVVM
  https://www.youtube.com/watch?v=7n2QprcdHMA Flutter News App (MVVM Architecture Study) PART 1 - Speed Code
  https://www.youtube.com/watch?v=cY9VMlxfV9Y Flutter News App (MVVM Architecture Study) PART 2 - Speed Code
  https://github.com/PuzzleLeaf/flutter_mvvm_tutorial/tree/master/01.news
  https://www.youtube.com/watch?v=6l2jDERA5eI Flutter NewsCloud App -Using MVVM pattern with Provider | بالعربي
  https://github.com/tharwatsamy/news_cloud
