MVVM pattern
  https://www.youtube.com/watch?v=W1e7d3cvnRo #Google Flutter - MVVM in Flutter using Providers.
  https://github.com/azamsharp/Movies-App-Flutter-MVVM
  https://www.youtube.com/watch?v=7n2QprcdHMA Flutter News App (MVVM Architecture Study) PART 1 - Speed Code
  https://www.youtube.com/watch?v=cY9VMlxfV9Y Flutter News App (MVVM Architecture Study) PART 2 - Speed Code
  https://github.com/PuzzleLeaf/flutter_mvvm_tutorial/tree/master/01.news
  https://www.youtube.com/watch?v=6l2jDERA5eI Flutter NewsCloud App -Using MVVM pattern with Provider | بالعربي
  https://github.com/tharwatsamy/news_cloud
  stream https://www.youtube.com/watch?v=Z2rGopxoZao Flutter Architecture Best Practices | Flutter Architecture MVVM | Flutter Architecture Tutorial
  mvvm getx https://github.com/muhammadarslannasr/MVVM-GETX-FLUTTER
  Getx mvvm firebase auth firestore https://github.com/PesaCoder/Ecommerce_App
  Provider mvvm https://github.com/shubham-chhimpa/flutter-mvvm-provider-demo

GetX
  Firestore Auth https://www.youtube.com/watch?v=BiV0DcXgk58 Firestore User with GetX | Todo App https://github.com/tadaspetra/getx_examples/tree/master/todo_app

  new push notification https://itnext.io/push-notifications-with-firebase-on-flutter-df68cc830c89
  ios fcm setup https://medium.com/inspireui/setup-firebase-cloud-messaging-fcm-push-notification-for-flutter-apps-8c767fe64e54
  
https://github.com/pinkeshdarji/FlutterCreateSubmissions2019 - flutter projects gallery
